version: '3.8'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: dziennik
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./log-reg__back-end
    env_file: 
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  frontend:
    build: ./log-reg_front-end
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
