version: '3.8'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: dziennik
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    env_file: 
      - .env
    environment:
      HOST_DB: mysql  # nazwa usługi MySQL w docker-compose
      USER_DB: root
      NAME_DB: dziennik
      PASS_DB: password
    ports:
      - "3001:3001"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
